- name: Basic raspberry configuration
  hosts: all
  become: true
  roles:
    - { role: 'basic-config', tags: 'basic-config' }

- name: Install docker 
  hosts: nodes 
  become: true
  vars:
    pip_package: python3-pip
  roles:
    - role: "geerlingguy.pip"
      tags: "docker"
    - role: "geerlingguy.docker_arm"
      tags: "docker"
      vars:
        docker_users:
          - pi

- name: Install Prometheus Node exporter service
  hosts: nodes
  roles:
  - role: 'node-exporter'
    tags: 'node-exporter'
    vars:
      node_listen: "{{ ansible_host }}"
