---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: Insert SSH key
  authorized_key: user=pi key={{ public_key }}
- name: Disable SSH Password Authentication 
  lineinfile:
    path: "/etc/ssh/sshd_config" 
    regex: ^(# *)?PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - restart sshd
- name: Remove nano
  apt: name=nano state=absent
- name: Install vim
  apt: name=vim state=present
