- name: enable prometheus
  become: true
  service:
      name: prometheus
      enabled: yes
      masked: no

- name: restart prometheus
  become: true
  service:
      name: prometheus
      state: restarted

